<a href="https://colab.research.google.com/github/MohammedWasi/DataScience-Essentials/blob/main/Day_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Questions 1:
Create a numpy array starting from 2 till 50 with a stepsize of 3.


In [1]:
import numpy as np

arr = np.arange(2,51,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


Questions 2:
Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.


In [2]:
list1=[]
list2=[]

for i in range(5):
  n = int(input("list 1 values"))
  list1.append(n)

for j in range(5):
  m = int(input("list 2 values"))
  list2.append(m)  


list 1 values2
list 1 values3
list 1 values4
list 1 values5
list 1 values6
list 2 values1
list 2 values7
list 2 values8
list 2 values5
list 2 values9


In [4]:
arr1 = np.array(list1)
arr2 = np.array(list2)

concat = np.concatenate((arr1,arr2))
print(concat)
sort = np.sort(concat)
print(sort)

[2 3 4 5 6 1 7 8 5 9]
[1 2 3 4 5 5 6 7 8 9]


Questions 3:
Write a code snippet to find the dimensions of a ndarray and its size.


In [5]:
import numpy as np

arr3 = np.array([[1, 4, 7], [3, 6, 9], [1, 4, 7], [3, 6, 9]])
print("calculating Dimensions of a nd array is :", arr3.ndim)

print("Size of an array is :", arr3.size)

calculating Dimensions of a nd array is : 2
Size of an array is : 12


Questions 4:
How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [9]:
import numpy as np

arr = np.arange(int(input()))
print(" 1D array:", arr.shape)

two_d_array_row = arr[np.newaxis]
print(" 2D array for row is :", two_d_array_row.shape)

two_d_array_col = arr[:, np.newaxis]
print(" 2D array for column is :", two_d_array_col.shape)

10
 1D array: (10,)
 2D array for row is : (1, 10)
 2D array for column is : (10, 1)


Questions 5:
Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()


In [20]:
import numpy as np

my_array_one = np.array([[1, 4, 5],[ 8, 79, 6],[ 3, 5, 7]])  
my_array_two = np.array([[4, 5, 8],[ 6, 9, 7],[ 4, 5, 6]])  

print(my_array_one)
print(my_array_two)

print()

print(" horizontally stacked :\n")
print( np.hstack((my_array_one, my_array_two)))
print()
print(" vertically stacked :\n")
print( np.vstack((my_array_one, my_array_two)))


[[ 1  4  5]
 [ 8 79  6]
 [ 3  5  7]]
[[4 5 8]
 [6 9 7]
 [4 5 6]]

 horizontally stacked :

[[ 1  4  5  4  5  8]
 [ 8 79  6  6  9  7]
 [ 3  5  7  4  5  6]]

 vertically stacked :

[[ 1  4  5]
 [ 8 79  6]
 [ 3  5  7]
 [ 4  5  8]
 [ 6  9  7]
 [ 4  5  6]]


Questions 6:
How to get unique items and counts of unique items?

In [25]:
import numpy as np

arr = np.array([4, 7, 8, 9, 5, 6, 5, 4, 4])

unique, counts = np.unique(arr, return_counts=True)
print(unique, counts)
print()
arr = np.asarray((unique, counts)).T
print(arr)

[4 5 6 7 8 9] [3 2 1 1 1 1]

[[4 3]
 [5 2]
 [6 1]
 [7 1]
 [8 1]
 [9 1]]
